Implement backends
ami-iit/ADAM pull request #3
Opened 2021-06-16 14:14 UTC by Giulero

2021-06-22 10:33 UTC, diegoferigo requested changes
Awesome!! What's not yet 100% clear is how the CasADI implementation of RBDAlgorithms could use the spatial operation implemented in numpy in the `AbstractTranforms` class. I'd expect that the graph gets broken if you don't use CasADI functions to perform slicing, matrix operations, ...

This is way I suggested to create real abstract base classes for the math and implement them for all different backends (casadi, numpy).

2021-06-22 10:33 UTC, diegoferigo commented on .github/workflows/tests.yml
> +          pytest --verbose
You can add the following to `setup.cfg`:

```cfg
[tool:pytest]
addopts = --capture=no --verbose
```

2021-06-22 10:33 UTC, diegoferigo commented on .github/workflows/tests.yml
>            pip install black
Maybe add `black` to the `test` extras_require?

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/transforms.py
> +        pass
This is not necessary in abstract base classes if there are no input parameters

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/transforms.py
> +    def R_from_axisAngle(self, axis, q):
Since there are no private attributes, all these methods could become class methods (i.e. replace `self` with `cls` in body).

```suggestion
    @classmethod
    def R_from_axisAngle(cls, axis, q):
```

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/transforms.py
> +        [cq, sq] = [np.cos(q), np.sin(q)]
```suggestion
        cq, sq = np.cos(q), np.sin(q)
```

no need for brackets

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/transforms.py
> +class AbstractTranforms(abc.ABC):
This seems to be more a `NumpyTransforms` rather than something abstract. Another general suggestion is to use `from scipy.spatial.transform import Rotation as R` for all the numpy-based SO3 operations. Be aware that quaternions are `xyzw` and not `wxyz`. See [`gym_ignition.rbd.conversions`](https://github.com/robotology/gym-ignition/blob/master/python/gym_ignition/rbd/conversions.py).

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/urdf_tree.py
> +    joints: list = field(default_factory=list)
If you:

```python
from typing import List
```

you can constrain:

```suggestion
    joints: List[str] = field(default_factory=list)
```

2021-06-22 10:33 UTC, diegoferigo commented on adam/geometry/utils.py
>  # GNU Lesser General Public License v2.1 or any later version.
This module could have a better structure if a more idiomatic pattern like class + static methods would be implemented, like [`gym_ignition.rbd.conversions`](https://github.com/robotology/gym-ignition/blob/master/python/gym_ignition/rbd/conversions.py) and [`gym_ignition.rbd.idyntree.numpy`](https://github.com/robotology/gym-ignition/blob/master/python/gym_ignition/rbd/idyntree/numpy.py).

2021-06-22 10:33 UTC, diegoferigo commented on adam/core/transforms.py
> +class AbstractTranforms(abc.ABC):
Ok, I finished checking all files and now the structure is more clear. What do you think of adding a real ABC that just declares the required methods, that could be a `SpatialMathABC` or similar.

Then, 1) the `RBDAlgorithms` could inherit from this ABC, 2) the spatial operation can be implemented in a `SpatialMathNumpy`, and 3) the final concrete class could be the following:

```
class NumPyKinDynComputations(RBDAlgorithms, SpatialMathNumpy):
```

This way, SpatialMathNumpy could be used also for other purpose as standalone class. It could even become more granular with Rotation, Transform, Quaternion, ...

2021-06-22 10:50 UTC, diegoferigo commented on adam/core/transforms.py
> +        [cq, sq] = [np.cos(q), np.sin(q)]
Other nit: stick with sneak case letters without mixing with camel case: `R_from_axis_angle`

2021-06-22 11:03 UTC, diegoferigo commented on adam/core/rbd_algorithms.py
> +    def rnea(self, T_b, q, v_b, q_dot, g):
Then, a final kwargs comment. It's debatable whether the kwargs should be as short or as descriptive as possible. Let's see the two cases:

#### 1. Short

Declaration:

```
def rnea(self, T_b, q, v_b, q_dot):
```

Usage:

```py
T_base = np.eye(4)
v_base = np.zeros(6)

q = np.zeros(dofs)
dq = np.zeros_like(q)

tau = obj.rnea(T_b=T_base, q=q, v_b=v_base, q_dot=dq)
```

#### Descriptive

Declaration

```
def rnea(self, base_transform, joint_positions, joint_velocities):
```

Usage:

```py
T_base = np.eye(4)
v_base = np.zeros(6)

q = np.zeros(dofs)
dq = np.zeros_like(q)

tau = obj.rnea(base_transform=T_base, joint_positions=q, base_velocity=v_base, joint_velocities=dq)
```

---

I personally prefer the descriptive approach of kwargs, it makes the code much more readable while still permits to use symbols for the variables.

2021-06-22 11:16 UTC, diegoferigo commented on adam/core/transforms.py
> +        T = self.eye(4)
I fear that using the `T` symbol for both the transform and generic Python type will soon fire us back. Maybe using `H` for the transforms?

2021-10-21 16:50 UTC, Giulero commented
Thanks @diegoferigo! I tried to follow the suggestions :)
Sadly for the jax and the pytorch interfaces I had some problems. Jax does not support mutable types, and for the assignments to slices of matrices and vectors I had to use [`index_update`](https://jax.readthedocs.io/en/latest/_autosummary/jax.ops.index_update.html). For some methods, I had to basically copy-paste some algorithms and change the required parts of the code.

2021-11-12 13:52 UTC, Giulero commented
@diegoferigo thanks for all the suggestions! I did some general cleanup. Still, I have to remove the duplicated algorithms for Jax computations. I would like to merge this PR and open a new one to address this task since it seems interestingly not super easy. What do you think? 
In this case, I'll open an issue to track this activity!

2021-11-14 14:54 UTC, diegoferigo approved these changes
Yes, we can fix the jax backend in a new PR. Just check the last comment I left.

2021-11-14 14:54 UTC, diegoferigo commented on adam/core/spatial_math.py
> +    @abc.abstractmethod
@Giulero are you sure these methods work as expected? If you don't mark them as `@staticmethod`, the first argument must be `self`.

2021-11-14 17:02 UTC, Giulero commented on adam/core/spatial_math.py
> +    @abc.abstractmethod
Mmm, everything seems fine since tests don't fail! :D 
Anyway, I fixed this in a970956 :)

2021-11-14 17:03 UTC, Giulero commented
Thanks @diegoferigo! :)
I checked your last comment, merging!

2021-11-14 17:06 UTC, merged

2021-11-14 17:16 UTC, diegoferigo commented on adam/core/spatial_math.py
> +    @abc.abstractmethod
Btw, those methods are designed to be static, what I meant was using [the following](https://docs.python.org/3/library/abc.html#abc.abstractmethod) instead of `self`:

```python
    @staticmethod
    @abstractmethod
    def R_from_axis_angle(axis, q):
```

Sorry if I didn't provide many details in my last reply.